/**
 * Created by feichongzheng on 17/9/25.
 */
export const CHANGE_ID_FOR_UNIFY_GROUP = 'UNIFYGROUP/CHANGEID';
export const CHANGE_ACTIVE_FOR_UNIFY_GROUP = 'UNIFYGROUP/CHANGEACTIVE';
export const FIND_BY_ID_FOR_UNIFY_GROUP = 'UNIFYGROUP/FINDBYID';
export const FIND_BY_ID_FOR_UNIFY_GROUP_FETCH = 'UNIFYGROUP/FINDBYIDFETCH';
export const FIND_BY_ID_FOR_UNIFY_GROUP_SUCCESS = 'UNIFYGROUP/FINDBYIDSUCCESS';
export const FIND_BY_ID_FOR_UNIFY_GROUP_ERROR = 'UNIFYGROUP/FINDBYIDERROR';
export const SHOW_UPDATE_PAGE_FOR_UNIFY_GROUP = 'UNIFYGROUP/SHOWUPDATEPAGE';
export const UPDATE_FOR_UNIFY_GROUP = 'UNIFYGROUP/UPDATE';
export const UPDATE_FOR_UNIFY_GROUP_FETCH = 'UNIFYGROUP/UPDATEFETCH';
export const UPDATE_FOR_UNIFY_GROUP_SUCCESS = 'UNIFYGROUP/UPDATESUCCESS';
export const UPDATE_FOR_UNIFY_GROUP_ERROR = 'UNIFYGROUP/UPDATEERROR';
