/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_CONTROLLERRESOURCE_FOR_TREE_TABLE = 'CONTROLLERRESOURCE/FINDFORTREETABLE';
export const FIND_CONTROLLERRESOURCE_FOR_TREE_TABLE_FETCH = 'CONTROLLERRESOURCE/FINDFORTREETABLEFETCH';
export const FIND_CONTROLLERRESOURCE_FOR_TREE_TABLE_SUCCESS = 'CONTROLLERRESOURCE/FINDFORTREETABLESUCCESS';
export const FIND_CONTROLLERRESOURCE_FOR_TREE_TABLE_ERROR = 'CONTROLLERRESOURCE/FINDFORTREETABLEERROR';
export const EXPAND_CONTROLLERRESOURCE_FOR_TREE_TABLE = 'CONTROLLERRESOURCE/EXPANDFORTREETABLE';
