/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_ASSIGN_PERSON_FOR_PAGE = 'ASSIGNPERSON/FINDFORPAGE';
export const FIND_ASSIGN_PERSON_FOR_PAGE_FETCH = 'ASSIGNPERSON/FINDFORPAGEFETCH';
export const FIND_ASSIGN_PERSON_FOR_PAGE_SUCCESS = 'ASSIGNPERSON/FINDFORPAGESUCCESS';
export const FIND_ASSIGN_PERSON_FOR_PAGE_ERROR = 'ASSIGNPERSON/FINDFORPAGEERROR';
export const SELECT_ROW_KEYS_FOR_ASSIGN_PERSON = 'ASSIGNPERSON/SELECTROWKEYS';
