/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_ROLE_FOR_PAGE = 'ROLE/FINDFORPAGE';
export const FIND_ROLE_FOR_PAGE_FETCH = 'ROLE/FINDFORPAGEFETCH';
export const FIND_ROLE_FOR_PAGE_SUCCESS = 'ROLE/FINDFORPAGESUCCESS';
export const FIND_ROLE_FOR_PAGE_ERROR = 'ROLE/FINDFORPAGEERROR';
