/**
 * Created by feichongzheng on 17/9/25.
 */
export const CHANGE_ID_FOR_UNIFY_CONTROLLER = 'UNIFYCONTROLLER/CHANGEID';
export const FIND_BY_ID_FOR_UNIFY_CONTROLLER = 'UNIFYCONTROLLER/FINDBYID';
export const FIND_BY_ID_FOR_UNIFY_CONTROLLER_FETCH = 'UNIFYCONTROLLER/FINDBYIDFETCH';
export const FIND_BY_ID_FOR_UNIFY_CONTROLLER_SUCCESS = 'UNIFYCONTROLLER/FINDBYIDSUCCESS';
export const FIND_BY_ID_FOR_UNIFY_CONTROLLER_ERROR = 'UNIFYCONTROLLER/FINDBYIDERROR';
export const SHOW_UPDATE_PAGE_FOR_UNIFY_CONTROLLER = 'UNIFYCONTROLLER/SHOWUPDATEPAGE';
export const UPDATE_FOR_UNIFY_CONTROLLER = 'UNIFYCONTROLLER/UPDATE';
export const UPDATE_FOR_UNIFY_CONTROLLER_FETCH = 'UNIFYCONTROLLER/UPDATEFETCH';
export const UPDATE_FOR_UNIFY_CONTROLLER_SUCCESS = 'UNIFYCONTROLLER/UPDATESUCCESS';
export const UPDATE_FOR_UNIFY_CONTROLLER_ERROR = 'UNIFYCONTROLLER/UPDATEERROR';
