/**
 * Created by feichongzheng on 17/9/25.
 */
export const CHANGE_ID_FOR_UNIFY_MENU = 'UNIFYMENU/CHANGEID';
export const CHANGE_ACTIVE_FOR_UNIFY_MENU = 'UNIFYMENU/CHANGEACTIVE';
export const FIND_BY_ID_FOR_UNIFY_MENU = 'UNIFYMENU/FINDBYID';
export const FIND_BY_ID_FOR_UNIFY_MENU_FETCH = 'UNIFYMENU/FINDBYIDFETCH';
export const FIND_BY_ID_FOR_UNIFY_MENU_SUCCESS = 'UNIFYMENU/FINDBYIDSUCCESS';
export const FIND_BY_ID_FOR_UNIFY_MENU_ERROR = 'UNIFYMENU/FINDBYIDERROR';
export const SHOW_UPDATE_PAGE_FOR_UNIFY_MENU = 'UNIFYMENU/SHOWUPDATEPAGE';
export const UPDATE_FOR_UNIFY_MENU = 'UNIFYMENU/UPDATE';
export const UPDATE_FOR_UNIFY_MENU_FETCH = 'UNIFYMENU/UPDATEFETCH';
export const UPDATE_FOR_UNIFY_MENU_SUCCESS = 'UNIFYMENU/UPDATESUCCESS';
export const UPDATE_FOR_UNIFY_MENU_ERROR = 'UNIFYMENU/UPDATEERROR';