/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_MENURESOURCE_FOR_TREE_TABLE = 'MENURESOURCE/FINDFORTREETABLE';
export const FIND_MENURESOURCE_FOR_TREE_TABLE_FETCH = 'MENURESOURCE/FINDFORTREETABLEFETCH';
export const FIND_MENURESOURCE_FOR_TREE_TABLE_SUCCESS = 'MENURESOURCE/FINDFORTREETABLESUCCESS';
export const FIND_MENURESOURCE_FOR_TREE_TABLE_ERROR = 'MENURESOURCE/FINDFORTREETABLEERROR';
export const EXPAND_MENURESOURCE_FOR_TREE_TABLE = 'MENURESOURCE/EXPANDFORTREETABLE';
