/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_GROUP_FOR_PAGE = 'GROUP/FINDFORPAGE';
export const FIND_GROUP_FOR_PAGE_FETCH = 'GROUP/FINDFORPAGEFETCH';
export const FIND_GROUP_FOR_PAGE_SUCCESS = 'GROUP/FINDFORPAGESUCCESS';
export const FIND_GROUP_FOR_PAGE_ERROR = 'GROUP/FINDFORPAGEERROR';
