/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_ASSIGN_USER_FOR_PAGE = 'ASSIGNUSER/FINDFORPAGE';
export const FIND_ASSIGN_USER_FOR_PAGE_FETCH = 'ASSIGNUSER/FINDFORPAGEFETCH';
export const FIND_ASSIGN_USER_FOR_PAGE_SUCCESS = 'ASSIGNUSER/FINDFORPAGESUCCESS';
export const FIND_ASSIGN_USER_FOR_PAGE_ERROR = 'ASSIGNUSER/FINDFORPAGEERROR';
export const SELECT_ROW_KEYS_FOR_ASSIGN_USER = 'ASSIGNUSER/SELECTROWKEYS';
