/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_ORG_FOR_TREE_TABLE = 'ORG/FINDFORTREETABLE';
export const FIND_ORG_FOR_TREE_TABLE_FETCH = 'ORG/FINDFORTREETABLEFETCH';
export const FIND_ORG_FOR_TREE_TABLE_SUCCESS = 'ORG/FINDFORTREETABLESUCCESS';
export const FIND_ORG_FOR_TREE_TABLE_ERROR = 'ORG/FINDFORTREETABLEERROR';
export const EXPAND_ORG_FOR_TREE_TABLE = 'ORG/EXPANDFORTREETABLE';
