/**
 * Created by feichongzheng on 17/9/25.
 */
export const CHANGE_ID_FOR_UNIFY_PERSON = 'UNIFYPERSON/CHANGEID';
export const FIND_BY_ID_FOR_UNIFY_PERSON = 'UNIFYPERSON/FINDBYID';
export const FIND_BY_ID_FOR_UNIFY_PERSON_FETCH = 'UNIFYPERSON/FINDBYIDFETCH';
export const FIND_BY_ID_FOR_UNIFY_PERSON_SUCCESS = 'UNIFYPERSON/FINDBYIDSUCCESS';
export const FIND_BY_ID_FOR_UNIFY_PERSON_ERROR = 'UNIFYPERSON/FINDBYIDERROR';
export const SHOW_UPDATE_PAGE_FOR_UNIFY_PERSON = 'UNIFYPERSON/SHOWUPDATEPAGE';
export const UPDATE_FOR_UNIFY_PERSON = 'UNIFYPERSON/UPDATE';
export const UPDATE_FOR_UNIFY_PERSON_FETCH = 'UNIFYPERSON/UPDATEFETCH';
export const UPDATE_FOR_UNIFY_PERSON_SUCCESS = 'UNIFYPERSON/UPDATESUCCESS';
export const UPDATE_FOR_UNIFY_PERSON_ERROR = 'UNIFYPERSON/UPDATEERROR';