/**
 * Created by feichongzheng on 17/9/25.
 */
export const CHANGE_ID_FOR_UNIFY_ORG_ROLE = 'UNIFYORGROLE/CHANGEID';
export const CHANGE_ACTIVE_FOR_UNIFY_ORG_ROLE = 'UNIFYORGROLE/CHANGEACTIVE';
export const FIND_BY_ID_FOR_UNIFY_ORG_ROLE = 'UNIFYORGROLE/FINDBYID';
export const FIND_BY_ID_FOR_UNIFY_ORG_ROLE_FETCH = 'UNIFYORGROLE/FINDBYIDFETCH';
export const FIND_BY_ID_FOR_UNIFY_ORG_ROLE_SUCCESS = 'UNIFYORGROLE/FINDBYIDSUCCESS';
export const FIND_BY_ID_FOR_UNIFY_ORG_ROLE_ERROR = 'UNIFYORGROLE/FINDBYIDERROR';
export const SHOW_UPDATE_PAGE_FOR_UNIFY_ORG_ROLE = 'UNIFYORGROLE/SHOWUPDATEPAGE';
export const UPDATE_FOR_UNIFY_ORG_ROLE = 'UNIFYORGROLE/UPDATE';
export const UPDATE_FOR_UNIFY_ORG_ROLE_FETCH = 'UNIFYORGROLE/UPDATEFETCH';
export const UPDATE_FOR_UNIFY_ORG_ROLE_SUCCESS = 'UNIFYORGROLE/UPDATESUCCESS';
export const UPDATE_FOR_UNIFY_ORG_ROLE_ERROR = 'UNIFYORGROLE/UPDATEERROR';