/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_ORG_STRUCTURE_IN_TREE = 'ORGSTRUCTURE/FINDINTREE';
export const FIND_ORG_STRUCTURE_IN_TREE_FETCH = 'ORGSTRUCTURE/FINDINTREEFETCH';
export const FIND_ORG_STRUCTURE_IN_TREE_SUCCESS = 'ORGSTRUCTURE/FINDINTREESUCCESS';
export const FIND_ORG_STRUCTURE_IN_TREE_ERROR = 'ORGSTRUCTURE/FINDINTREEERROR';
export const EXPANDKEYS_FOR_ORG_STRUCTURE = 'ORGSTRUCTURE/EXPANDKEYS';
export const SEARCH_FOR_ORG_STRUCTURE = 'ORGSTRUCTURE/SEARCH';
export const UPDATE_RENDER_FOR_ORG_STRUCTURE = 'ORGSTRUCTURE/UPDATERENDER';
