/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_UNASSIGN_PERSON_FOR_PAGE = 'UNASSIGNPERSON/FINDFORPAGE';
export const FIND_UNASSIGN_PERSON_FOR_PAGE_FETCH = 'UNASSIGNPERSON/FINDFORPAGEFETCH';
export const FIND_UNASSIGN_PERSON_FOR_PAGE_SUCCESS = 'UNASSIGNPERSON/FINDFORPAGESUCCESS';
export const FIND_UNASSIGN_PERSON_FOR_PAGE_ERROR = 'UNASSIGNPERSON/FINDFORPAGEERROR';
export const SELECT_ROW_KEYS_FOR_UN_ASSIGN_PERSON = 'UNASSIGNPERSON/SELECTROWKEYS';
