/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_ORGROLE_FOR_PAGE = 'ORGROLE/FINDFORPAGE';
export const FIND_ORGROLE_FOR_PAGE_FETCH = 'ORGROLE/FINDFORPAGEFETCH';
export const FIND_ORGROLE_FOR_PAGE_SUCCESS = 'ORGROLE/FINDFORPAGESUCCESS';
export const FIND_ORGROLE_FOR_PAGE_ERROR = 'ORGROLE/FINDFORPAGEERROR';
