/**
 * Created by feichongzheng on 17/9/25.
 */
export const CHANGE_ID_FOR_UNIFY_ORG = 'UNIFYORG/CHANGEID';
export const CHANGE_ACTIVE_FOR_UNIFY_ORG = 'UNIFYORG/CHANGEACTIVE';
export const FIND_BY_ID_FOR_UNIFY_ORG = 'UNIFYORG/FINDBYID';
export const FIND_BY_ID_FOR_UNIFY_ORG_FETCH = 'UNIFYORG/FINDBYIDFETCH';
export const FIND_BY_ID_FOR_UNIFY_ORG_SUCCESS = 'UNIFYORG/FINDBYIDSUCCESS';
export const FIND_BY_ID_FOR_UNIFY_ORG_ERROR = 'UNIFYORG/FINDBYIDERROR';
export const SHOW_UPDATE_PAGE_FOR_UNIFY_ORG = 'UNIFYORG/SHOWUPDATEPAGE';
export const UPDATE_FOR_UNIFY_ORG = 'UNIFYORG/UPDATE';
export const UPDATE_FOR_UNIFY_ORG_FETCH = 'UNIFYORG/UPDATEFETCH';
export const UPDATE_FOR_UNIFY_ORG_SUCCESS = 'UNIFYORG/UPDATESUCCESS';
export const UPDATE_FOR_UNIFY_ORG_ERROR = 'UNIFYORG/UPDATEERROR';