/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_PERSON_FOR_PAGE = 'PERSON/FINDFORPAGE';
export const FIND_PERSON_FOR_PAGE_FETCH = 'PERSON/FINDFORPAGEFETCH';
export const FIND_PERSON_FOR_PAGE_SUCCESS = 'PERSON/FINDFORPAGESUCCESS';
export const FIND_PERSON_FOR_PAGE_ERROR = 'PERSON/FINDFORPAGEERROR';
