/**
 * Created by feichongzheng on 17/9/25.
 */
export const CHANGE_ID_FOR_UNIFY_APP = 'UNIFYAPP/CHANGEID';
export const CHANGE_ACTIVE_FOR_UNIFY_APP = 'UNIFYAPP/CHANGEACTIVE';
export const FIND_BY_ID_FOR_UNIFY_APP = 'UNIFYAPP/FINDBYID';
export const FIND_BY_ID_FOR_UNIFY_APP_FETCH = 'UNIFYAPP/FINDBYIDFETCH';
export const FIND_BY_ID_FOR_UNIFY_APP_SUCCESS = 'UNIFYAPP/FINDBYIDSUCCESS';
export const FIND_BY_ID_FOR_UNIFY_APP_ERROR = 'UNIFYAPP/FINDBYIDERROR';
export const SHOW_UPDATE_PAGE_FOR_UNIFY_APP = 'UNIFYAPP/SHOWUPDATEPAGE';
export const UPDATE_FOR_UNIFY_APP = 'UNIFYAPP/UPDATE';
export const UPDATE_FOR_UNIFY_APP_FETCH = 'UNIFYAPP/UPDATEFETCH';
export const UPDATE_FOR_UNIFY_APP_SUCCESS = 'UNIFYAPP/UPDATESUCCESS';
export const UPDATE_FOR_UNIFY_APP_ERROR = 'UNIFYAPP/UPDATEERROR';
