/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_RESOURCE_STRUCTURE_IN_TREE = 'RESOURCESTRUCTURE/FINDINTREE';
export const FIND_RESOURCE_STRUCTURE_IN_TREE_FETCH = 'RESOURCESTRUCTURE/FINDINTREEFETCH';
export const FIND_RESOURCE_STRUCTURE_IN_TREE_SUCCESS = 'RESOURCESTRUCTURE/FINDINTREESUCCESS';
export const FIND_RESOURCE_STRUCTURE_IN_TREE_ERROR = 'RESOURCESTRUCTURE/FINDINTREEERROR';
export const EXPANDKEYS_FOR_RESOURCE_STRUCTURE = 'RESOURCESTRUCTURE/EXPANDKEYS';
export const SEARCH_FOR_RESOURCE_STRUCTURE = 'RESOURCESTRUCTURE/SEARCH';
export const CHECKKEYS_FOR_RESOURCE_STRUCTURE = 'RESOURCESTRUCTURE/CHECKKEYS';
export const FIND_AUTHED_FOR_RESOURCE_STRUCTURE = 'RESOURCESTRUCTURE/FINDAUTHED';
export const FIND_AUTHED_FOR_RESOURCE_STRUCTURE_SUCCESS = 'RESOURCESTRUCTURE/FINDAUTHEDSUCCESS';
export const CHANGECHECKABLE_FOR_RESOURCE_STRUCTURE = 'RESOURCESTRUCTURE/CHANGECHECKABLE';
