/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_POSITION_FOR_PAGE = 'POSITION/FINDFORPAGE';
export const FIND_POSITION_FOR_PAGE_FETCH = 'POSITION/FINDFORPAGEFETCH';
export const FIND_POSITION_FOR_PAGE_SUCCESS = 'POSITION/FINDFORPAGESUCCESS';
export const FIND_POSITION_FOR_PAGE_ERROR = 'POSITION/FINDFORPAGEERROR';
