/**
 * Created by feichongzheng on 17/9/25.
 */
export const CHANGE_ID_FOR_UNIFY_POSITION = 'UNIFYPOSITION/CHANGEID';
export const CHANGE_ACTIVE_FOR_UNIFY_POSITION = 'UNIFYPOSITION/CHANGEACTIVE';
export const FIND_BY_ID_FOR_UNIFY_POSITION = 'UNIFYPOSITION/FINDBYID';
export const FIND_BY_ID_FOR_UNIFY_POSITION_FETCH = 'UNIFYPOSITION/FINDBYIDFETCH';
export const FIND_BY_ID_FOR_UNIFY_POSITION_SUCCESS = 'UNIFYPOSITION/FINDBYIDSUCCESS';
export const FIND_BY_ID_FOR_UNIFY_POSITION_ERROR = 'UNIFYPOSITION/FINDBYIDERROR';
export const SHOW_UPDATE_PAGE_FOR_UNIFY_POSITION = 'UNIFYPOSITION/SHOWUPDATEPAGE';
export const UPDATE_FOR_UNIFY_POSITION = 'UNIFYPOSITION/UPDATE';
export const UPDATE_FOR_UNIFY_POSITION_FETCH = 'UNIFYPOSITION/UPDATEFETCH';
export const UPDATE_FOR_UNIFY_POSITION_SUCCESS = 'UNIFYPOSITION/UPDATESUCCESS';
export const UPDATE_FOR_UNIFY_POSITION_ERROR = 'UNIFYPOSITION/UPDATEERROR';