/**
 * Created by feichongzheng on 17/9/25.
 */
export const FIND_UNASSIGN_USER_FOR_PAGE = 'UNASSIGNUSER/FINDFORPAGE';
export const FIND_UNASSIGN_USER_FOR_PAGE_FETCH = 'UNASSIGNUSERUSER/FINDFORPAGEFETCH';
export const FIND_UNASSIGN_USER_FOR_PAGE_SUCCESS = 'UNASSIGNUSER/FINDFORPAGESUCCESS';
export const FIND_UNASSIGN_USER_FOR_PAGE_ERROR = 'UNASSIGNUSER/FINDFORPAGEERROR';
export const SELECT_ROW_KEYS_FOR_UN_ASSIGN_USER = 'UNASSIGNUSER/SELECTROWKEYS';
