/**
 * Created by feichongzheng on 17/9/25.
 */
export const CHANGE_APP_FOR_AUTH = 'AUTH/CHANGEAPP';
export const CHANGE_MENU_FOR_AUTH = 'AUTH/CHANGEMENU';

export const EXPAND_MENU_FOR_AUTH = 'AUTH/EXPANDMENU';
export const CHECK_MENU_FOR_AUTH = 'AUTH/CHECKMENU';
export const SELECT_MENU_FOR_AUTH = 'AUTH/SELECTMENU';

export const FIND_MENU_FOR_AUTH = 'AUTH/FINDMENU';
export const FIND_MENU_FOR_AUTH_FETCH = 'AUTH/FINDMENUFETCH';
export const FIND_MENU_FOR_AUTH_SUCCESS = 'AUTH/FINDMENUSUCCESS';
export const FIND_MENU_FOR_AUTH_ERROR = 'AUTH/FINDMENUERROR';

export const EXPAND_CONTROLLER_FOR_AUTH = 'AUTH/EXPANDCONTROLLER';
export const CHECK_CONTROLLER_FOR_AUTH = 'AUTH/CHECKCONTROLLER';
export const SELECT_CONTROLLER_FOR_AUTH = 'AUTH/SELECTCONTROLLER';

export const FIND_CONTROLLER_FOR_AUTH = 'AUTH/FINDCONTROLLER';
export const FIND_CONTROLLER_FOR_AUTH_FETCH = 'AUTH/FINDCONTROLLERFETCH';
export const FIND_CONTROLLER_FOR_AUTH_SUCCESS = 'AUTH/FINDCONTROLLERSUCCESS';
export const FIND_CONTROLLER_FOR_AUTH_ERROR = 'AUTH/FINDCONTROLLERERROR';
